# -*- coding: utf-8 -*-
"""kesetimbangan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qeouAbblQ9LpfoRedXlIoQGEs7-MmfAY
"""

import numpy as np
import matplotlib.pyplot as plt

#rentang nilai x dan waktu untuk medan vektor
x = np.arange(0, 3, 0.1)
t = np.arange(0, 4, 0.1)
T, X = np.meshgrid(t, x)

# Definisikan sistem
dX =-X**2 + 3 * X - 2
dT = np.ones(dX.shape)

# Plot stream plot
plt.figure(figsize=(10, 6))
plt.streamplot(T, X, dT, dX, color=dX, cmap='coolwarm', linewidth=1)

plt.title("Stream Plot of the System")
plt.xlabel("Time (t)")
plt.ylabel("x")
plt.axhline(0, color='gray', linestyle='--')
plt.colorbar(label='dx/dt')
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
# Parameter konstanta
k = 0.1 # Konstanta pendinginan
Ta = 25 # Suhu lingkungan
import numpy as np
import matplotlib.pyplot as plt
# Parameter konstanta
k = 0.1 # Konstanta pendinginan
Ta = 25 # Suhu lingkungan

# Definisikan sistem persamaan diferensial
def system(T):
    return -k * (T - Ta)

# Membuat grid untuk visualisasi
t_vals = np.linspace(0, 50, 20)
T_vals = np.linspace(0, 50, 20)
t, T = np.meshgrid(t_vals, T_vals)

# Menghitung Vektor arah
U = np.ones_like(T)
V = system(T)

# Plot medan vektor menggunakan steamplot
plt.figure(figsize=(7, 5))
plt.streamplot(t, T, U, V, color='blue')
plt.axhline(Ta, color='red', linestyle='--', label='Solusi Setimbang (T = Ta)')
plt.xlabel('t(waktu)')
plt.ylabel('T(suhu)')
plt.title('Medan Vektor untuk Persamaan Diferensial Pendinginan Newton')
plt.legend()
plt.grid()
plt.show()
# Membuat grid untuk visualisasi
t_vals = np.linspace(0, 50, 20)
T_vals = np.linspace(0, 50, 20)
t, T = np.meshgrid(t_vals, T_vals)

# Menghitung Vektor arah
U = np.ones_like(T)
V = system(T)

# Plot medan vektor menggunakan steamplot
plt.figure(figsize=(7, 5))
plt.streamplot(t, T, U, V, color='blue')
plt.axhline(Ta, color='red', linestyle='--', label='Solusi Setimbang (T = Ta)')
plt.xlabel('t(waktu)')
plt.ylabel('T(suhu)')
plt.title('Medan Vektor untuk Persamaan Diferensial Pendinginan Newton')
plt.legend()
plt.grid()
plt.show()