# -*- coding: utf-8 -*-
"""praktikum3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JD99CyToyZIhkqNkH9gt2axMs5Z05Sju
"""

import numpy as np

A = np.array([[-2, -2],
              [7,7]])
nilaieigen, vectoreigen = np.linalg.eig(A)
print("nilaieigen:")
print(nilaieigen)
print("\nvectoreigen")
print(vectorseigen)