# -*- coding: utf-8 -*-
"""SEIR tanpa laju kelahiran dan kematian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_RjEPgsEcRRAqgpOfUMITiY0N8B_tWyi
"""

# Model SEIR tanpa laju kelahiran dan kematian
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

# Parameter epidemiologi untuk DBD
beta = 0.5            # Laju penularan DBD
sigma = 1/7           # Masa inkubasi DBD (7 hari)
gamma = 1/10          # Masa sembuh (10 hari)

# populasi
N = 1000

# Kondisi awal
S0 = N - 1  # Susceptible (Rentan)
E0 = 0      # Exposed (Terpapar)
I0 = 1      # Infected (Terinfeksi)
R0 = 0      # Recovered (Sembuh)

# Waktu simulasi (hari)
t = np.linspace(0, 160, 160)

# Fungsi SEIR Model
def seir_model(y, t, N, beta, sigma, gamma):
    S, E, I, R = y
    dSdt = -beta * S * I / N
    dEdt = beta * S * I / N - sigma * E
    dIdt = sigma * E - gamma * I
    dRdt = gamma * I
    return [dSdt, dEdt, dIdt, dRdt]

# Inisialisasi kondisi awal
y0 = [S0, E0, I0, R0]

# Solusi numerik
solution = odeint(seir_model, y0, t, args=(N, beta, sigma, gamma))
S, E, I, R = solution.T

# Plot hasil simulasi
plt.figure(figsize=(10, 6))
plt.plot(t, S, label='Susceptible', color='blue')
plt.plot(t, E, label='Exposed', color='orange')
plt.plot(t, I, label='Infected', color='red')
plt.plot(t, R, label='Recovered', color='green')
plt.xlabel('Hari')
plt.ylabel('Jumlah Individu')
plt.title('Simulasi Model SEIR untuk DBD (Demam Berdarah)')
plt.legend()
plt.grid()
plt.show()