# -*- coding: utf-8 -*-
"""SEIR dengan kelahiran dan kematian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yy4Z3Lwf3US1b55Iy-hL10JqVfXEebKT
"""

# Model SEIR dengan kelahiran dan kematian (Kasus DBD)
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

# Parameter epidemiologi DBD
beta = 0.3               # Laju penularan DBD
sigma = 1/6               # Masa inkubasi (6 hari)
gamma = 1/10               # Lama sembuh (10 hari)

# Parameter demografi
alpha = 0.01              # Laju kelahiran (misal 1% dari populasi per hari)
delta = 0.005             # Laju kematian alami (misal 0.5% per hari)

# Ukuran populasi awal
N = 1000

# Kondisi awal
S0 = N - 20
E0 = 15
I0 = 5
R0 = 0

# Waktu simulasi (hari)
t = np.linspace(0, 200, 200)

# Fungsi Model SEIR dengan kelahiran & kematian
def seir_model_dbd(y, t, N, beta, sigma, gamma, alpha, delta):
    S, E, I, R = y
    dSdt = alpha * N - beta * S * I / N - delta * S
    dEdt = beta * S * I / N - sigma * E - delta * E
    dIdt = sigma * E - gamma * I - delta * I
    dRdt = gamma * I - delta * R
    return [dSdt, dEdt, dIdt, dRdt]

# Inisialisasi kondisi awal
y0 = [S0, E0, I0, R0]

# Solusi numerik pakai odeint
solution = odeint(seir_model_dbd, y0, t, args=(N, beta, sigma, gamma, alpha, delta))
S, E, I, R = solution.T

# Plot hasil simulasi
plt.figure(figsize=(10, 6))
plt.plot(t, S, label='Rentan (Susceptible)', color='blue')
plt.plot(t, E, label='Terekspos (Exposed)', color='orange')
plt.plot(t, I, label='Terinfeksi (Infected)', color='red')
plt.plot(t, R, label='Sembuh (Recovered)', color='green')
plt.xlabel('Hari')
plt.ylabel('Jumlah Individu')
plt.title('Simulasi Model SEIR untuk Kasus DBD (dengan Kelahiran & Kematian)')
plt.legend()
plt.grid()
plt.show()